### ISSUE TITLE
Connection retrying issue

### ISSUE THREAD

**Issue by venserwub** [RocketChat/Rocket.Chat.Electron#179]
## My Setup

*Mac OSX: 10.11.3
- RocketChat Desktop Client: 1.3.1

docker-compose.yml: 

```
devchat:
  hostname: devchat.test.com
  image: rocketchat/rocket.chat:latest
  net: devchat
  ports:
    - 3000:3000
  environment:
    - "MONGO_URL=mongodb://devchatmongo/rocketchat"
    - "ROOT_URL=https://devchat.test.com"
    - "ADMIN_PASS=supersecret"
    - "ADMIN_EMAIL=admin@admin.com"

database:
  container_name: devchatmongo
  image: mongo
  net: devchat
  volumes:
    - "/var/lib/rocketchat/data/runtime/db:/data/db"
    - "/var/lib/rocketchat/data/dump:/dump"
  command: mongod --smallfiles
```
- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

I was testing rocket chat and have run into issues with the client trying to reconnect every x seconds. The issue happens every time I try to login. I saw the issue #71 which seemed to have the same problem but occurred randomly. The fix on that issue was to update the desktop client, however I am running 1.3.1 and still have the same problem.

I am running the compose file given above against a ubuntu trusty64 machine using docker 1.10. 
#### Current Behavior

The client is stuck reconnecting every x seconds, and will not allow logins.
The issue is occurring in both the desktop client as well as the web client.
![screen shot 2016-04-22 at 11 13 54 am](https://cloud.githubusercontent.com/assets/6156092/14749211/6ccc446c-087b-11e6-9877-7fed4e0fd6f3.png)
![screen shot 2016-04-22 at 11 15 33 am](https://cloud.githubusercontent.com/assets/6156092/14749236/9910cb06-087b-11e6-8b26-538f2e4a3949.png)
#### Expected Behavior

Everything works as expected when running on a docker-machine vm, but when I try to run it on my server the connection issue arrises. 
##
